import React,{useState} from 'react';
function rgb(h,s,v){const c=v*s,x=c*(1-Math.abs((h/60)%2-1)),m=v-c;const a=h<60?[c,x,0]:h<120?[x,c,0]:h<180?[0,c,x]:h<240?[0,x,c]:h<300?[x,0,c]:[c,0,x];return '#'+a.map(n=>Math.round((n+m)*255).toString(16).padStart(2,'0')).join('')}
function hsv(hex){const [r,g,b]=hex.slice(1).match(/../g).map(n=>parseInt(n,16)/255),v=Math.max(r,g,b),d=v-Math.min(r,g,b);let h=d===0?0:v===r?60*((g-b)/d%6):v===g?60*((b-r)/d+2):60*((r-g)/d+4);return [h<0?h+360:h,v?d/v:0,v]}
export default function ColorPicker({value,onChange,label}){
 const [open,setOpen]=useState(false),[hue,setHue]=useState(()=>hsv(value)[0]),[code,setCode]=useState(value);
 const [h,s,v]=hsv(value),currentHue=s?h:hue;
 function change(hh,ss,vv){setHue(hh);const next=rgb(hh,ss,vv);setCode(next);onChange(next)}
 function point(e){const r=e.currentTarget.getBoundingClientRect();change(currentHue,Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),1-Math.max(0,Math.min(1,(e.clientY-r.top)/r.height)))}
 return <div className="color-picker"><button className="secondary" aria-expanded={open} onClick={()=>{setCode(value);setOpen(!open)}}><span className="chosen-color" style={{background:value}}/>색상 직접 선택</button>{open&&<div className="color-picker-panel" aria-label={`${label} 선택창`}><div className="color-picker-main"><div className="color-square" style={{backgroundColor:rgb(currentHue,1,1)}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);point(e)}} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))point(e)}}><span style={{left:`${s*100}%`,top:`${(1-v)*100}%`}}/></div><input className="hue-slider" aria-label={`${label} 색조`} type="range" min="0" max="359" value={currentHue} onChange={e=>change(Number(e.target.value),s,v)}/></div><label>채도<input aria-label={`${label} 채도`} type="range" min="0" max="100" value={Math.round(s*100)} onChange={e=>change(currentHue,Number(e.target.value)/100,v)}/></label><label>밝기<input aria-label={`${label} 밝기`} type="range" min="0" max="100" value={Math.round(v*100)} onChange={e=>change(currentHue,s,Number(e.target.value)/100)}/></label><label>색상 코드<input aria-label={`${label} 색상 코드`} value={code} maxLength={7} spellCheck={false} onChange={e=>{setCode(e.target.value);if(/^#[0-9a-f]{6}$/i.test(e.target.value))onChange(e.target.value)}} onBlur={()=>setCode(value)}/></label><button className="primary" onClick={()=>setOpen(false)}>선택 완료</button></div>}</div>
}
