export const VERSION='1.0.0';
export const HOME='https://unfmarketing.com';
export const CHAT='https://pf.kakao.com/_zWEMxb/chat';
export const tag=s=>'#'+String(s||'').replace(/[^\p{L}\p{N}_]/gu,'');
export const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
export const defaults=()=>({org:'',phone:'',type:'주간보호센터',date:today(),activity:'',description:'',region:'',category:'미술 활동',theme:'clean',font:'Jua',color:'#ffffff',textBackground:false,textBackgroundColor:'#172554',textBackgroundOpacity:.85,size:1,gradient:true,shadow:true,outline:true,textPosition:'bottom',brandPosition:'top',showOrg:true,showPhone:true,brandScope:'all',inquiry:'이용·입소문의',fit:'contain',duration:30,quality:1080,music:'none',originalAudio:false,credit:false,ending:true});
export function caption(s){const [,m,d]=s.date.split('-');return [`${Number(m)}월 ${Number(d)}일 ${s.org}`,`${tag(s.type)} ${s.activity} 프로그램`,s.description.trim(),[s.org,s.activity,s.region].filter(Boolean).map(tag).filter((v,i,a)=>a.indexOf(v)===i).join(' ')].filter(Boolean).join('\n\n').replace(/일 ([^\n]+)\n\n/, '일 $1\n');}
export const phrases={'미술 활동':['함께하는 미술 활동','오늘의 작품을 소개합니다','손끝으로 표현하는 시간'],'신체 활동':['함께하는 신체 활동','오늘의 활동을 소개합니다','함께 움직이는 시간'],'요리 활동':['함께하는 요리 활동','오늘의 요리를 소개합니다','정성을 담는 시간'],'생신잔치':['생신을 축하드립니다','축하의 마음을 전합니다','함께하는 생신잔치'],'일상':['우리 기관의 하루','오늘의 일상을 소개합니다','함께하는 시간'],'직접 입력':['오늘의 프로그램','활동 현장을 소개합니다','함께하는 시간']};
export function suggestion(s,i=0){return (phrases[s.category]||phrases['직접 입력'])[i%3]}
export function schedule(clips,s){const available=Number(s.duration)-(s.ending?3:0), share=available/Math.max(1,clips.length);let offset=0;return clips.map(c=>{const length=Math.floor((c.kind==='video'?Math.min(c.end-c.start,share):share)*24)/24;const item={...c,length,offset};offset+=length;return item})}
export function rectAt(mask,t){const a=mask.points.slice().sort((a,b)=>a.t-b.t);if(!a.length)return null;if(t<a[0].t)return a[0];for(let i=1;i<a.length;i++){if(t<=a[i].t){const f=(t-a[i-1].t)/(a[i].t-a[i-1].t||1);return Object.fromEntries(['x','y','w','h'].map(k=>[k,a[i-1][k]+(a[i][k]-a[i-1][k])*f]))}}return a.at(-1)}
export const EVENTS=new Set(['visit','media_ready','analysis_start','analysis_done','edit','render_start','render_done','render_cancel','save_request','save_confirm','copy','consult','homepage','share','error']);
export const CODES=new Set(['NONE','FILE_UNSUPPORTED','FILE_LIMIT','MODEL_FAILED','DECODE_FAILED','ENCODE_FAILED','PLAYBACK_FAILED','SAVE_FAILED','UNSUPPORTED_BROWSER','HIDDEN','UNKNOWN']);
export function sanitizeEvent(body){if(!body||!EVENTS.has(body.event))return null;const safe={event:body.event,version:VERSION};if(/^[a-f0-9-]{16,40}$/.test(body.job||''))safe.job=body.job;if(CODES.has(body.code))safe.code=body.code;for(const key of ['count','seconds','elapsed','width','height'])if(Number.isFinite(body[key])&&body[key]>=0&&body[key]<=1e7)safe[key]=Math.round(body[key]);for(const [k,values]of Object.entries({os:['ios','android','mac','windows','other'],browser:['safari','chrome','samsung','firefox','other'],source:['direct','kakao','website','shared'],size:['small','medium','large']}))if(values.includes(body[k]))safe[k]=body[k];return safe}

export function formatPhone(value){const n=value.replace(/\D/g,'');if(n.length===8)return n.replace(/(\d{4})(\d{4})/,'$1-$2');if(n.startsWith('02')&&n.length===9)return n.replace(/(\d{2})(\d{3})(\d{4})/,'$1-$2-$3');if(n.startsWith('02')&&n.length===10)return n.replace(/(\d{2})(\d{4})(\d{4})/,'$1-$2-$3');if(n.length===10)return n.replace(/(\d{3})(\d{3})(\d{4})/,'$1-$2-$3');if(n.length===11)return n.replace(/(\d{3})(\d{4})(\d{4})/,'$1-$2-$3');return value}
