import {FaceDetector,FilesetResolver} from '@mediapipe/tasks-vision';
import {Input,BlobSource,ALL_FORMATS,CanvasSink,AudioBufferSink,Output,Mp4OutputFormat,BufferTarget,CanvasSource,AudioBufferSource,canEncodeVideo,canEncodeAudio} from 'mediabunny';
import {rectAt,schedule} from './core.mjs';
let detectorPromise;
export function detector(){return detectorPromise??=(async()=>{try{const fs=await FilesetResolver.forVisionTasks('/wasm');return await FaceDetector.createFromOptions(fs,{baseOptions:{modelAssetPath:'/models/face.tflite'},runningMode:'IMAGE',minDetectionConfidence:.35})}catch(e){detectorPromise=null;throw e}})()}
function detect(d,source){const width=source.width||source.videoWidth,height=source.height||source.videoHeight;const boxes=[];function collect(src,x=0,y=0,w=width,h=height){for(const a of d.detect(src).detections){const b=a.boundingBox;boxes.push({x:(x+b.originX/src.width*w)/width,y:(y+b.originY/src.height*h)/height,w:b.width/src.width*w/width,h:b.height/src.height*h/height})}}collect(source);const tile=document.createElement('canvas');tile.width=384;tile.height=384;const ctx=tile.getContext('2d');const edge=Math.min(width,height)*.7;for(const [u,v]of [[0,0],[1,0],[0,1],[1,1],[.5,.5]]){const x=(width-edge)*u,y=(height-edge)*v;ctx.drawImage(source,x,y,edge,edge,0,0,384,384);collect(tile,x,y,edge,edge)}return boxes.filter((b,i)=>!boxes.slice(0,i).some(a=>{const overlap=Math.max(0,Math.min(a.x+a.w,b.x+b.w)-Math.max(a.x,b.x))*Math.max(0,Math.min(a.y+a.h,b.y+b.h)-Math.max(a.y,b.y));return overlap/Math.min(a.w*a.h,b.w*b.h)>.55}))}
export async function loadFile(file){const url=URL.createObjectURL(file),kind=file.type.startsWith('image/')?'image':'video';try{if(kind==='image'){const image=new Image();image.src=url;await image.decode();if(image.width*image.height>50e6)throw Error('FILE_LIMIT');return {id:crypto.randomUUID(),file,url,kind,image,width:image.width,height:image.height,start:0,end:60,caption:'',masks:[],auto:[],analyzed:false}}const input=new Input({source:new BlobSource(file),formats:ALL_FORMATS});const track=await input.getPrimaryVideoTrack();if(!track||!await track.canDecode())throw Error('FILE_UNSUPPORTED');const duration=await input.computeDuration();if(!Number.isFinite(duration)||duration>180)throw Error('FILE_LIMIT');const sink=new CanvasSink(track,{width:960});return {id:crypto.randomUUID(),file,url,kind,input,sink,width:track.displayWidth,height:track.displayHeight,duration,start:0,end:Math.min(duration,15),caption:'',masks:[],auto:[],analyzed:false}}catch(e){URL.revokeObjectURL(url);throw e}}
export async function sourceAt(c,t){if(c.kind==='image')return c.image;const r=await c.sink.getCanvas(Math.max(0,Math.min(c.duration-.001,t)));if(!r)throw Error('DECODE_FAILED');return r.canvas}
export async function analyze(c,onProgress,signal){const d=await detector();if(c.kind==='image'){return [{t:0,boxes:detect(d,c.image)}]}const frames=[];const step=1/6;const times=Array.from({length:Math.ceil((c.end-c.start)/step)+1},(_,i)=>Math.min(c.end-.001,c.start+i*step));let i=0;for await(const r of c.sink.canvasesAtTimestamps(times)){if(signal?.aborted)throw new DOMException('Canceled','AbortError');if(!r)throw Error('DECODE_FAILED');frames.push({t:times[i],boxes:detect(d,r.canvas)});onProgress(++i/times.length);if(i%4===0)await new Promise(resolve=>setTimeout(resolve,0))}return frames}
export function boxesAt(c,t){if(!c.auto.length)return [];if(c.kind==='image')return c.auto[0].boxes;let i=c.auto.findIndex(f=>f.t>=t);if(i<0)i=c.auto.length-1;return [...c.auto[Math.max(0,i-1)].boxes,...c.auto[i].boxes]}
export function followMask(c,mask){let previous=mask.points[0];const points=[previous];for(const frame of c.auto.filter(a=>a.t>previous.t)){let best=null,dist=.22;for(const b of frame.boxes){const d=Math.hypot((b.x+b.w/2)-(previous.x+previous.w/2),(b.y+b.h/2)-(previous.y+previous.h/2));if(d<dist){dist=d;best=b}}if(best){previous={t:frame.t,...best};points.push(previous)}}return {...mask,points}}
function lines(ctx,text,maxWidth,max=3){const result=[];let line='';for(const char of String(text)){if(char==='\n'||ctx.measureText(line+char).width>maxWidth){result.push(line);line=char==='\n'?'':char}else line+=char}if(line)result.push(line);if(result.length>max){result.length=max;result[max-1]=result[max-1].slice(0,-1)+'…'}return result}
export function draw(canvas,source,c,s,t,{ending=false,guides=false,selected=null}={}){const ctx=canvas.getContext('2d'),W=canvas.width,H=canvas.height,scale=W/1080;ctx.clearRect(0,0,W,H);ctx.fillStyle=s.theme==='warm'?'#8d442d':s.theme==='bright'?'#287454':'#131d39';ctx.fillRect(0,0,W,H);let fit;
if(source&&!ending){const sw=source.width||source.videoWidth,sh=source.height||source.videoHeight;const ratio=s.fit==='cover'?Math.max(W/sw,H/sh):Math.min(W/sw,H/sh);const w=sw*ratio,h=sh*ratio,x=(W-w)*(c.panX??.5),y=(H-h)*(c.panY??.5);fit={x,y,w,h};ctx.drawImage(source,x,y,w,h);const masks=[...boxesAt(c,t).map(b=>({...b,auto:true})),...c.masks.filter(m=>t>=m.from&&t<=m.to).map(m=>({...rectAt(m,t),id:m.id}))];for(const b of masks){const pad=b.auto?.24:.05;const bx=Math.max(0,x+(b.x-b.w*pad)*w),by=Math.max(0,y+(b.y-b.h*pad)*h),bw=Math.min(W-bx,b.w*(1+pad*2)*w),bh=Math.min(H-by,b.h*(1+pad*2)*h);if(bw<=0||bh<=0)continue;const tmp=document.createElement('canvas');tmp.width=Math.max(2,Math.ceil(bw/(30*scale)));tmp.height=Math.max(2,Math.ceil(bh/(30*scale)));const tc=tmp.getContext('2d');tc.drawImage(canvas,bx,by,bw,bh,0,0,tmp.width,tmp.height);ctx.imageSmoothingEnabled=false;ctx.drawImage(tmp,0,0,tmp.width,tmp.height,bx,by,bw,bh);ctx.imageSmoothingEnabled=true;if(guides&&b.id===selected){ctx.strokeStyle='#a9f071';ctx.lineWidth=4*scale;ctx.strokeRect(bx,by,bw,bh)}}}
const dark=s.theme==='bright'?'#06351f':'#071020';if(s.gradient&&!ending){let g=ctx.createLinearGradient(0,H*.55,0,H);g.addColorStop(0,'transparent');g.addColorStop(1,dark+'ee');ctx.fillStyle=g;ctx.fillRect(0,H*.55,W,H*.45);let top=ctx.createLinearGradient(0,0,0,H*.22);top.addColorStop(0,dark+'cc');top.addColorStop(1,'transparent');ctx.fillStyle=top;ctx.fillRect(0,0,W,H*.22)}
ctx.textAlign='center';ctx.textBaseline='middle';const font=s.font==='Noto Serif KR'?'Noto Serif KR':'Noto Sans KR';function text(value,y,size,max=3,color=s.color){ctx.font=`700 ${size*scale}px "${font}"`;ctx.fillStyle=color;ctx.shadowColor=s.shadow?'#000a':'transparent';ctx.shadowBlur=s.shadow?10*scale:0;ctx.shadowOffsetY=s.shadow?3*scale:0;const arr=lines(ctx,value,W-130*scale,max);arr.forEach((l,i)=>{const yy=y+i*size*1.4*scale;if(s.outline){ctx.lineWidth=4*scale;ctx.strokeStyle='#0008';ctx.strokeText(l,W/2,yy)}ctx.fillText(l,W/2,yy)});ctx.shadowBlur=0;ctx.shadowOffsetY=0;return arr.length*size*1.4*scale}
if(ending){if(s.showOrg)text(s.org||'우리 기관',H*.38,64,3);if(s.showPhone&&s.phone){text(s.inquiry,H*.58,40,1);text(s.phone,H*.65,61,2)}if(s.credit)text('제작 도구 제공 · 낯선마케팅',H*.84,25,1,'#ffffff');return fit}
if(s.logoImage){const lh=H*.045,lw=Math.min(W*.22,lh*s.logoImage.width/s.logoImage.height);ctx.drawImage(s.logoImage,(W-lw)/2,H*.025,lw,lh)}const by=s.brandPosition==='top'?H*.11:H*.79;if(s.brandScope==='all'){let offset=0;if(s.showOrg&&s.org)offset=text(s.org,by,39,2);if(s.showPhone&&s.phone)text(`${s.inquiry} ${s.phone}`,by+offset,32,2)}
let ty=s.textPosition==='top'?H*.24:s.textPosition==='center'?H*.43:H*.64;if(s.brandPosition==='bottom'&&s.textPosition==='bottom')ty=H*.52;const used=text(s.activity||'오늘의 프로그램',ty,65*s.size,3);if(c.caption)text(c.caption,ty+used+26*scale,38*s.size,3);if(s.credit)text('낯선클립',H*.94,22,1,'#ffffff');return fit}
export async function supported(width=1080){return canEncodeVideo('avc',{width,height:width*16/9,bitrate:4e6})}
async function soundtrack(items,s,total,signal){if(s.music==='none'&&!s.originalAudio)return null;if(!await canEncodeAudio('aac',{sampleRate:44100,numberOfChannels:2}))throw Error('AUDIO_UNSUPPORTED');const rate=44100,buffer=new AudioBuffer({length:Math.ceil(total*rate),sampleRate:rate,numberOfChannels:2});if(s.music!=='none'){const notes=s.music==='bright'?[261.63,329.63,392,523.25,440,392,329.63,293.66]:[261.63,329.63,392,329.63,220,261.63,329.63,261.63];for(let i=0;i<buffer.length;i++){const t=i/rate,beat=Math.floor(t/.65),p=t%.65,fade=Math.min(1,t,total-t),v=(Math.sin(2*Math.PI*notes[beat%notes.length]*t)+.3*Math.sin(4*Math.PI*notes[beat%notes.length]*t))*.06*Math.exp(-p*5)*Math.min(1,p/.02)*Math.max(0,fade);buffer.getChannelData(0)[i]=v;buffer.getChannelData(1)[i]=v}}
if(s.originalAudio)for(const c of items){if(signal.aborted)throw new DOMException('Canceled','AbortError');if(c.kind!=='video')continue;const track=await c.input.getPrimaryAudioTrack();if(!track)continue;if(!await track.canDecode())throw Error('AUDIO_DECODE_FAILED');for await(const wrapped of new AudioBufferSink(track).buffers(c.start,c.start+c.length)){const a=wrapped.buffer;for(let ch=0;ch<2;ch++){const target=buffer.getChannelData(ch),data=a.getChannelData(Math.min(ch,a.numberOfChannels-1));const start=Math.max(0,Math.ceil((c.start-wrapped.timestamp)*a.sampleRate)),end=Math.min(a.length,Math.floor((c.start+c.length-wrapped.timestamp)*a.sampleRate));for(let n=start;n<end;n++){const dest=Math.round((c.offset+wrapped.timestamp+n/a.sampleRate-c.start)*rate);if(dest>=0&&dest<target.length)target[dest]=Math.max(-1,Math.min(1,target[dest]+data[n]*.8))}}}}
return buffer}
export async function renderVideo(clips,s,onProgress,signal){const W=Number(s.quality);if(!await supported(W))throw Error('UNSUPPORTED_BROWSER');await document.fonts.ready;const items=schedule(clips,s),duration=items.reduce((a,c)=>a+c.length,0)+(s.ending?3:0);const audio=await soundtrack(items,s,duration,signal);const canvas=document.createElement('canvas');canvas.width=W;canvas.height=W*16/9;const target=new BufferTarget(),output=new Output({format:new Mp4OutputFormat({fastStart:'in-memory'}),target});const videoSource=new CanvasSource(canvas,{codec:'avc',bitrate:W===1080?5e6:2.5e6});output.addVideoTrack(videoSource,{frameRate:24});let audioSource;if(audio){audioSource=new AudioBufferSource({codec:'aac',bitrate:128000});output.addAudioTrack(audioSource)}let wake;try{wake=await navigator.wakeLock?.request('screen')}catch{}let frame=0;try{await output.start();if(audio)await audioSource.add(audio);for(const c of items){const frames=Math.round(c.length*24),times=Array.from({length:frames},(_,i)=>c.start+i/24);let iterator=c.kind==='video'?c.sink.canvasesAtTimestamps(times):null;for(let i=0;i<frames;i++){if(signal.aborted)throw new DOMException('Canceled','AbortError');const source=iterator?(await iterator.next()).value?.canvas:c.image;if(!source)throw Error('DECODE_FAILED');draw(canvas,source,c,s,times[i]);await videoSource.add(frame/24,1/24);frame++;if(i%4===0){onProgress(Math.min(.99,frame/(duration*24)));await new Promise(r=>setTimeout(r,0))}}}if(s.ending)for(let i=0;i<72;i++){if(signal.aborted)throw new DOMException('Canceled','AbortError');draw(canvas,null,items.at(-1),s,0,{ending:true});await videoSource.add(frame++/24,1/24);if(i%8===0)await new Promise(r=>setTimeout(r,0))}videoSource.close();audioSource?.close();await output.finalize();onProgress(1);return {blob:new Blob([target.buffer],{type:'video/mp4'}),duration:frame/24}}catch(e){if(output.state!=='finalized'&&output.state!=='canceled')await output.cancel();throw e}finally{await wake?.release()}}
